/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_Andersen */

#ifndef _Included_svfjava_Andersen
#define _Included_svfjava_Andersen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_Andersen
 * Method:    create
 * Signature: (Lsvfjava/SVFIR;)Lsvfjava/Andersen;
 */
JNIEXPORT jobject JNICALL Java_svfjava_Andersen_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     svfjava_Andersen
 * Method:    getPTACallGraph
 * Signature: ()Lsvfjava/PTACallGraph;
 */
JNIEXPORT jobject JNICALL Java_svfjava_Andersen_getPTACallGraph
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
