/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFG */

#ifndef _Included_svfjava_SVFG
#define _Included_svfjava_SVFG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFG
 * Method:    dump
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_svfjava_SVFG_dump
  (JNIEnv *, jobject, jstring);

/*
 * Class:     svfjava_SVFG
 * Method:    getFormalParameter
 * Signature: (Lsvfjava/SVFValue;)Lsvfjava/VFGNode;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFG_getFormalParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     svfjava_SVFG
 * Method:    getFunctionFormalParameter
 * Signature: (Lsvfjava/SVFFunction;I)Lsvfjava/VFGNode;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFG_getFunctionFormalParameter
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
