/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFIR */

#ifndef _Included_svfjava_SVFIR
#define _Included_svfjava_SVFIR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFIR
 * Method:    getGNode
 * Signature: (Lsvfjava/PointsTo;)Lsvfjava/SVFVar;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFIR_getGNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     svfjava_SVFIR
 * Method:    getValueNode
 * Signature: (Lsvfjava/SVFValue;)Lsvfjava/NodeID;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFIR_getValueNode
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
