/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFModule */

#ifndef _Included_svfjava_SVFModule
#define _Included_svfjava_SVFModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFModule
 * Method:    createSVFModule
 * Signature: (Ljava/lang/String;)Lsvfjava/SVFModule;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFModule_createSVFModule
  (JNIEnv *, jclass, jstring);

/*
 * Class:     svfjava_SVFModule
 * Method:    getFunctions
 * Signature: ()[Lsvfjava/SVFFunction;
 */
JNIEXPORT jobjectArray JNICALL Java_svfjava_SVFModule_getFunctions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
