/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_PointsTo */

#ifndef _Included_svfjava_PointsTo
#define _Included_svfjava_PointsTo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_PointsTo
 * Method:    toStringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_svfjava_PointsTo_toStringNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
