/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFIRBuilder */

#ifndef _Included_svfjava_SVFIRBuilder
#define _Included_svfjava_SVFIRBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFIRBuilder
 * Method:    create
 * Signature: (Lsvfjava/SVFModule;)Lsvfjava/SVFIRBuilder;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFIRBuilder_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     svfjava_SVFIRBuilder
 * Method:    build
 * Signature: ()Lsvfjava/SVFIR;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFIRBuilder_build
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
