/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_VFGNode */

#ifndef _Included_svfjava_VFGNode
#define _Included_svfjava_VFGNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_VFGNode
 * Method:    toStringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_svfjava_VFGNode_toStringNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
