/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFModule */

#ifndef _Included_svfjava_SVFModule
#define _Included_svfjava_SVFModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFModule
 * Method:    createSVFModule
 * Signature: (Ljava/lang/String;Lsvfjava/SVFAnalysisListener;)Lsvfjava/SVFModule;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFModule_createSVFModule
        (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     svfjava_SVFModule
 * Method:    getFunctions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_svfjava_SVFModule_getFunctions
        (JNIEnv *, jobject);

/*
 * Class:     svfjava_SVFModule
 * Method:    getFunctionArgCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_svfjava_SVFModule_getFunctionArgCount
        (JNIEnv *, jobject, jstring);

/*
 * Class:     svfjava_SVFModule
 * Method:    processFunction
 * Signature: (Ljava/lang/String;[J[[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_svfjava_SVFModule_processFunction
        (JNIEnv *, jobject, jstring, jlongArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
