/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_VFG */

#ifndef _Included_svfjava_VFG
#define _Included_svfjava_VFG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_VFG
 * Method:    create
 * Signature: (Lsvfjava/PTACallGraph;)Lsvfjava/VFG;
 */
JNIEXPORT jobject JNICALL Java_svfjava_VFG_create
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
