/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFValue */

#ifndef _Included_svfjava_SVFValue
#define _Included_svfjava_SVFValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFValue
 * Method:    toStringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_svfjava_SVFValue_toStringNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
