/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFFunction */

#ifndef _Included_svfjava_SVFFunction
#define _Included_svfjava_SVFFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFFunction
 * Method:    getArgumentsNative
 * Signature: ()[Lsvfjava/SVFArgument;
 */
JNIEXPORT jobjectArray JNICALL Java_svfjava_SVFFunction_getArgumentsNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
