/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFGBuilder */

#ifndef _Included_svfjava_SVFGBuilder
#define _Included_svfjava_SVFGBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFGBuilder
 * Method:    create
 * Signature: ()Lsvfjava/SVFGBuilder;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFGBuilder_create
  (JNIEnv *, jclass);

/*
 * Class:     svfjava_SVFGBuilder
 * Method:    buildFullSVFG
 * Signature: (Lsvfjava/Andersen;)Lsvfjava/SVFG;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFGBuilder_buildFullSVFG
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
