/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFVar */

#ifndef _Included_svfjava_SVFVar
#define _Included_svfjava_SVFVar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFVar
 * Method:    getValue
 * Signature: ()Lsvfjava/SVFValue;
 */
JNIEXPORT jobject JNICALL Java_svfjava_SVFVar_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
