/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class svfjava_SVFJava */

#ifndef _Included_svfjava_SVFJava
#define _Included_svfjava_SVFJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     svfjava_SVFJava
 * Method:    runmain
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_svfjava_SVFJava_runmain
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
